import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Link from 'next/link';

export default function Home () {
    return (<div className={ styles.container }>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <div className={ styles.main }>
            <h1>home page</h1>
            <ul>
                {/* adding a link through a traditional route will resend an http request to reload page -  */ }
                {/* thus loosing all state -  */ }
                {/* <li><a href="/portfolio">Portfolio</a></li> */ }

                {/* next uses a <Link/> component, very similar to ReactRouter -  */ }
                {/* using this router avoids a complete refresh of the SPA -  */ }

                {/* fun-fact ::Link keyword. replace - does not allow user to go back to the previous page -  */ }
                <li><Link href={ "/portfolio" }>Portfolio</Link></li>
                <li><Link href={ '/clients' }>Clients</Link></li>

            </ul>

        </div>

        <footer className={ styles.footer }>

        </footer>
    </div>)
}
